# Generated by Django 4.2.28 on 2026-02-26 18:15

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sprite_url', models.URLField(blank=True, max_length=500, null=True)),
                ('types', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('encounter_location', models.CharField(blank=True, max_length=255, null=True)),
                ('recent_moves', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_pokemon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
